# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'php_choose'
      prompt: "Choose serial number to install PHP \n
      1: PHP 5.6\n
      2: PHP 7.0\n
      3: PHP 7.1\n
      4: PHP 7.2\n
      5: PHP 7.3 (unavailable)\n
      6: PHP 7.4 (unavailable)\n"
      private: no
      default: 4

    - name: 'mysql_choose'
      prompt: "Choose serial number to install MySQL \n
      1: MySQL 5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL MySQL5.6(only for CentOS7.x, AmazonLinux, Ubuntu16.04 )\n
      3: MySQL 5.7\n
      4: MySQL 8.0\n"
      private: no
      default: 3

  vars:
    select_mysql_ver:
      '1': "5.5"
      '2': "5.6"
      '3': "5.7"
      '4': "8.0"
    select_php_ver:
      '1': "5.6"
      '2': "7.0"
      '3': "7.1"
      '4': "7.2"
      '5': "7.3"

    mysql_version: "{{select_mysql_ver[mysql_choose]}}"
    php_version: "{{select_php_ver[php_choose]}}"
    
  tasks:
    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1
    
    - debug:
       msg: "hello is installing now"
      

