# this ci file include special build task
# if you replace it, please remember to migrate Job: vuepress build for LAMP and Installation

name: Docs Build and Upload

on: 
  push:
    paths: docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: npm install vuepress
      run: |
       sudo npm install -g vuepress
        
    - name: vuepress build for LAMP and Installation
      run: |
        cd docs
        sudo vuepress build
        ls
        sudo rm -rf html/lamp/installation
        ls
        cd installation
        sudo vuepress build
        ls
        sudo cp -r -f html/installation ./html/lamp/
      env:
        CI: true
    
    #  to azure blob
    - name: debug
      run: ls
    - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
      with:
        source_dir: docs/html
        container_name: $web
        connection_string: ${{ secrets.Azure_blob }}
        extra_args: '--destination-path docs'
        sync: false
